FROM python:3.11-slim

RUN pip install --no-cache-dir \
    colorama==0.4.6 \
    coverage==7.10.6 \
    mutmut==2.4.5 \
    pytest==8.4.2 \
    pytest-cov==7.0.0 \
    pytest-json-report==1.5.0 \
    whatthepatch==1.0.7

WORKDIR /app/input
